run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - revive          # reasonable style checker
    - errcheck
    - gosec           # light security scan

linters-settings:
  revive:
    ignore-generated-header: true
